spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    #username: gilxyj
    #password: sdfm1234
    url: jdbc:mysql://127.0.0.1:33306/vhr?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  jpa:
    properties:
      show-sql: true
      database: mysql
      database-platform: mysql
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL57Dialect
  http:
    encoding:
      force-response: true
      force-request: true
      charset: UTF-8
  profiles:
    #active: dev
    active: prod
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

server:
  port: 8080
