server:
  port: 8081
spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: hdyajocutmotbdig
    username: 852753482@qq.com
    port: 587
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.133.128
    port: 5672

