spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: gilxyj
    password: sdfm1234
  jpa:
    properties:
      show-sql: true
      database: mysql
      database-platform: mysql
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL57Dialect
  http:
    encoding:
      force-response: true
      force-request: true
      charset: UTF-8
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
